name: CI

on:
  push:
    branches: [ '*', '!master' ]
  workflow_dispatch:

defaults:
  run:
    shell: bash
jobs:
  cloudtasks:
    name: Build CloudTasks Emulator
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-cloudtasks
          key: ${{ runner.os }}-buildx-cloudtasks-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-cloudtasks
      - name: Build CloudTasks emulator
        uses: docker/build-push-action@v2
        with:
          context: ./cloudtasks-emulator
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache-cloudtasks
          cache-to: type=local,dest=/tmp/.buildx-cache-cloudtasks

  cloud-storage:
    name: Build Cloud Storage Emulator
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-cloudstorage
          key: ${{ runner.os }}-buildx-cloudstorage-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-cloudstorage-
      - name: Build Cloud Storage emulator
        uses: docker/build-push-action@v2
        with:
          context: ./cloudstorage-emulator
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache-cloudstorage
          cache-to: type=local,dest=/tmp/.buildx-cache-cloudstorage

  datastore:
    name: Build Datastore Emulator
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-datastore
          key: ${{ runner.os }}-buildx-datastore-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-datastore-
      - name: Build Datastore emulator
        uses: docker/build-push-action@v2
        with:
          context: ./datastore-emulator
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache-datastore
          cache-to: type=local,dest=/tmp/.buildx-cache-datastore

  firebase:
    name: Build Firebase Emulator
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-firebase
          key: ${{ runner.os }}-buildx-firebase-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-firebase-
      - name: Build and Push Firebase emulator
        uses: docker/build-push-action@v2
        with:
          context: ./firebase-emulator
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache-firebase
          cache-to: type=local,dest=/tmp/.buildx-cache-firebase
