name: Build and Publish

on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:

defaults:
  run:
    shell: bash
jobs:
  cloudtasks:
    name: Build CloudTasks Emulator
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-cloudtasks
          key: ${{ runner.os }}-buildx-cloudtasks-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-cloudtasks-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push CloudTasks emulator
        uses: docker/build-push-action@v2
        with:
          context: ./cloudtasks-emulator
          push: true
          tags: spine3/cloudtasks-emulator:latest
          cache-from: type=local,src=/tmp/.buildx-cache-cloudtasks
          cache-to: type=local,dest=/tmp/.buildx-cache-cloudtasks
      - name: Update CloudTasks repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: spine3/cloudtasks-emulator
          readme-filepath: ./cloudtasks-emulator/README.md

  datastore:
    name: Build Datastore Emulator
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-datastore
          key: ${{ runner.os }}-buildx-datastore-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-datastore-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Datastore emulator
        uses: docker/build-push-action@v2
        with:
          context: ./datastore-emulator
          push: true
          tags: spine3/datastore-emulator:latest
          cache-from: type=local,src=/tmp/.buildx-cache-datastore
          cache-to: type=local,dest=/tmp/.buildx-cache-datastore
      - name: Update Datastore repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: spine3/datastore-emulator
          readme-filepath: ./datastore-emulator/README.md

  firebase:
    name: Build Firebase Emulator
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-firebase
          key: ${{ runner.os }}-buildx-firebase-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-firebase-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Firebase emulator
        uses: docker/build-push-action@v2
        with:
          context: ./firebase-emulator
          push: true
          tags: spine3/firebase-emulator:latest
          cache-from: type=local,src=/tmp/.buildx-cache-firebase
          cache-to: type=local,dest=/tmp/.buildx-cache-firebase
      - name: Update Datastore repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: spine3/firebase-emulator
          readme-filepath: ./firebase-emulator/README.md
